version: '3.9'

services:
    app:
        build:
            context: .
            dockerfile: ./backend/Dockerfile
        command: >
            sh -c "python manage.py migrate &&
                   python manage.py runserver 0.0.0.0:8000"
        ports:
            - 8000:8000
        volumes:
            - ./backend:/app
        environment:
            - SECRET_KEY=devsecretkey
            - DEBUG=1
            - DB_HOST=db
            - DB_NAME=devdb
            - DB_USER=devuser
            - DB_PASS=12345678
        depends_on:
            - db
    db:
        image: postgres:13-alpine
        environment:
            - POSTGRES_DB=devdb
            - POSTGRES_USER=devuser
            - POSTGRES_PASSWORD=12345678
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready']
            interval: 10s
            timeout: 5s
            retries: 18
